package com.l2.mvci.main;

public enum MainMessage {
    NONE,
    SEND_MESSAGE,
    FILE_DROPPED_SUCCESS,
    CONVERT_TO_SQL,
    PREP_CONV,
    CLOSE_APPLICATION,
    LOAD_WORKBOOK_REQUEST,
    BUILD_FINAL_DATABASE, UPDATE_OPTIONS
}